version: '3'
    
services:
    cardrivers:
        image: cardrivers:latest
        network_mode: "host"
        volumes:
            - "./Data:/home/cardrivers/Data"
            - "./scripts:/home/cardrivers/scripts"
            - "./cardrivers/catkin_ws:/home/cardrivers/catkin_ws"
        privileged: true
        environment: 
            - "DISABLE_CONTRACTS=1"
            - "ROS_MASTER_URI=http://localhost:11311"
            - "HOSTNAME=master"
        restart: "always"
        command: ["/home/cardrivers/scripts/start_rosbridge.sh"] 
        
    aidrivingmodule:
        image: enicky/aidrivingmodule:latest-arm32v7
        network_mode: "host"
        volumes:
            - "./Data:/home/aidrivingmodule/Data"
            - "../scripts:/scripts"
            - "./ai-driver:/ai-driver"
            - "./ai-driver/catkin_ws:/home/aidrivingmodule/catkin_ws"
            - "./scripts/run_ai_module.sh:/home/aidrivingmodule/run_ai_module.sh"
        environment: 
            - "DISABLE_CONTRACTS=1"
            - "ROS_MASTER_URI=http://localhost:11311"
            - "HOSTNAME=master"
        depends_on: 
            - cardrivers
        restart: "always"
        
    pi-comm:
        image: pi_comm
        network_mode: "host"
        volumes:
            - "./pi-comm/rttfcar_commander/:/home/user/rttfcar_commander/"
        privileged: true
        environment:
            - "DISABLE_CONTRACTS=1"
            - "ROS_MASTER_URI=http://localhost:11311"
            - "HOSTNAME=master"
        depends_on:
            - cardrivers
            - aidrivingmodule
        restart: "always"
#        command: "cd /home/user/pi-comm/ && /bin/bash start_picomm.sh"