version: '3'
    
services:
  cardrivers:
    image: enicky/cardrivers:latest-arm32v7
    ports:
        - "11311:11311"
    volumes:
        - "/data:/data"
    privileged: true
    environment: 
        - "DISABLE_CONTRACTS=1"
        - "ROS_MASTER_URI=http://localhost:11311"
        - "HOSTNAME=master"
    restart: "always"
    
  aidrivingmodule:
    image: enicky/aidrivingmodule:latest-arm32v7
    volumes:
        - "/data:/data"
    environment: 
        - "DISABLE_CONTRACTS=1"
        - "ROS_MASTER_URI=http://localhost:11311"
        - "HOSTNAME=master"
    depends_on: 
        - cardrivers
    restart: "always"
